services:
  - type: web
    name: viit-mart
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/viitmart.db
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
